### ISSUE TITLE
Not working with Vite

### ISSUE THREAD

**Issue by nahoc10** [avvydomains/js-client#7]

**Comment by connorbode** [comment]
Can you provide more context?

**Comment by connorbode** [comment]
The latest version, 3.0.2, removes the dependency which was causing a lot of problems in various environments (circomlibjs). Could be that this also resolves the issues in Vite.

**Comment by nahoc10** [comment]
> The latest version, 3.0.2, removes the dependency which was causing a lot of problems in various environments (circomlibjs). Could be that this also resolves the issues in Vite.

I will try again shortly, thanks
